resolver: lts-11.13

packages:
- libs/api-bot
- libs/api-client
- libs/bilge
- libs/brig-types
- libs/cargohold-types
- libs/cassandra-util
- libs/extended
- libs/galley-types
- libs/gundeck-types
- libs/http-client-openssl-ext
- libs/metrics-collectd
- libs/metrics-core
- libs/metrics-wai
- libs/ropes
- libs/sodium-crypto-sign
- libs/tasty-cannon
- libs/types-common
- libs/types-common-aws
- libs/types-common-journal
- libs/wai-utilities
- libs/zauth
- services/brig
- services/spar
- services/cannon
- services/cargohold
- services/galley
- services/gundeck
- services/proxy
- tools/bonanza
- tools/makedeb
- tools/api-simulations

- location:
    git: https://github.com/tiago-loureiro/haskell-multihash.git
    commit: 7622cfcff97fa1e207ec91bb11495a207e6c0195
  extra-dep: true

- location:
    git: https://github.com/wireapp/cryptobox-haskell
    commit: 7546a1a25635ef65183e3d44c1052285e8401608
  extra-dep: true

- location:
    git: https://github.com/kim/hs-collectd
    commit: '0.0.0.2'
  extra-dep: true

- location:
    git: https://github.com/kim/snappy-framing
    commit: d99f702c0086729efd6848dea8a01e5266c3a61c
  extra-dep: true

- location:
    git: https://github.com/tiago-loureiro/aws
    commit: 42695688fc20f80bf89cec845c57403954aab0a2
  extra-dep: true

- location:
    git: https://gitlab.com/twittner/wai-routing
    commit: 7e996a93fec5901767f845a50316b3c18e51a61d
  extra-dep: true

# The version on Haskage (0.9.0.2) deadlocks so here we're using master.
# See https://github.com/jwiegley/async-pool/issues/2
- location:
    git: https://github.com/jwiegley/async-pool
    commit: 5678c13c4ec7d96a55622f7171f8e6a6bb3a3947
  extra-dep: true

# Our fork gives us access to some guts that the upstream 'http-client'
# doesn't expose; see https://github.com/wireapp/wire-server/pull/373
- location:
    git: https://github.com/neongreen/http-client
    commit: 6a4ac55edf5e62574210c77a1468fa7accb81670
  subdirs:
  - http-client
  - http-client-openssl
  - http-client-tls
  - http-conduit
  extra-dep: true

# services/spar:
- location:
    git: https://github.com/wireapp/saml2-web-sso
    commit: abd1f80a518153026c5669bd4cd8117cb8716a20
  extra-dep: true
- location:
    git: https://github.com/wireapp/hsaml2
    commit: 8a91c880740232dbd52ff73efb99ea179c2338c7
  extra-dep: true
- location:
    git: https://github.com/wireapp/hspec-wai
    commit: ca10d13deab929f1cc3a569abea2e7fbe35fdbe3  # https://github.com/hspec/hspec-wai/pull/49
  extra-dep: true
- location:
    git: https://github.com/wireapp/servant-multipart
    commit: a5f0b9ce508f9d4c28a41d2b856387a7db281577  # https://github.com/haskell-servant/servant-multipart/pull/17
  extra-dep: true

extra-deps:
- base58-bytestring-0.1.0
- currency-codes-2.0.0.0
- data-timeout-0.3
- geoip2-0.3.1.0
- html-entities-1.1.4.1
- mime-0.4.0.2
- lens-labels-0.2.0.1
- proto-lens-0.3.1.0
- proto-lens-protoc-0.3.1.0
- snappy-0.2.0.2
- tasty-1.0.0.1
- text-icu-translit-0.1.0.7
- wai-middleware-gunzip-0.0.2
- HsOpenSSL-0.11.4.12
- invertible-hxt-0.1  # for hsaml2 / spar
- swagger2-2.2.1  # to get 'fromAesonOptions'

flags:
  types-common:
    cql: True
    protobuf: True
    arbitrary: True

extra-package-dbs: []

allow-newer: False
